//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GUI.servis {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceMojSoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceMoj : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback prijavaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RačuniKomitentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransakcijeKomitentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeznamTransakcijOperationCompleted;
        
        private System.Threading.SendOrPostCallback seznamRačunovOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeznamKomitentovOperationCompleted;
        
        private System.Threading.SendOrPostCallback vrniTransakcijeOperationCompleted;
        
        private System.Threading.SendOrPostCallback vrniKomitenteZTransakcijoOperationCompleted;
        
        private System.Threading.SendOrPostCallback transakcijeKomitentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback komitentOperationCompleted;
        
        private System.Threading.SendOrPostCallback IzpisBlokiranihRačunovOperationCompleted;
        
        private System.Threading.SendOrPostCallback NajvišjaTransakcijaOperationCompleted;
        
        private System.Threading.SendOrPostCallback povprecnaStarostKomitentovOperationCompleted;
        
        private System.Threading.SendOrPostCallback RačunPridobiOperationCompleted;
        
        private System.Threading.SendOrPostCallback KomitentShraniOperationCompleted;
        
        private System.Threading.SendOrPostCallback KomitentBrišiOperationCompleted;
        
        private System.Threading.SendOrPostCallback KomitentAžurirajOperationCompleted;
        
        private System.Threading.SendOrPostCallback KomitentPridobiOperationCompleted;
        
        private System.Threading.SendOrPostCallback RačunShraniOperationCompleted;
        
        private System.Threading.SendOrPostCallback RačunBrišiOperationCompleted;
        
        private System.Threading.SendOrPostCallback RačunAžurirajOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransakcijaShraniOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransakcijaBrišiOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransakcijaAžurirajOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransakcijaPridobiOperationCompleted;
        
        private System.Threading.SendOrPostCallback UporabniškiRačunShraniOperationCompleted;
        
        private System.Threading.SendOrPostCallback UporabniškiRačunBrišiOperationCompleted;
        
        private System.Threading.SendOrPostCallback UporabniškiRačunAžurirajOperationCompleted;
        
        private System.Threading.SendOrPostCallback UporabniškiRačunPridobiOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceMoj() {
            this.Url = global::GUI.Properties.Settings.Default.GUI_servis_WebServiceMoj;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event prijavaCompletedEventHandler prijavaCompleted;
        
        /// <remarks/>
        public event RačuniKomitentaCompletedEventHandler RačuniKomitentaCompleted;
        
        /// <remarks/>
        public event TransakcijeKomitentaCompletedEventHandler TransakcijeKomitentaCompleted;
        
        /// <remarks/>
        public event SeznamTransakcijCompletedEventHandler SeznamTransakcijCompleted;
        
        /// <remarks/>
        public event seznamRačunovCompletedEventHandler seznamRačunovCompleted;
        
        /// <remarks/>
        public event SeznamKomitentovCompletedEventHandler SeznamKomitentovCompleted;
        
        /// <remarks/>
        public event vrniTransakcijeCompletedEventHandler vrniTransakcijeCompleted;
        
        /// <remarks/>
        public event vrniKomitenteZTransakcijoCompletedEventHandler vrniKomitenteZTransakcijoCompleted;
        
        /// <remarks/>
        public event transakcijeKomitentaCompletedEventHandler transakcijeKomitentaCompleted;
        
        /// <remarks/>
        public event komitentCompletedEventHandler komitentCompleted;
        
        /// <remarks/>
        public event IzpisBlokiranihRačunovCompletedEventHandler IzpisBlokiranihRačunovCompleted;
        
        /// <remarks/>
        public event NajvišjaTransakcijaCompletedEventHandler NajvišjaTransakcijaCompleted;
        
        /// <remarks/>
        public event povprecnaStarostKomitentovCompletedEventHandler povprecnaStarostKomitentovCompleted;
        
        /// <remarks/>
        public event RačunPridobiCompletedEventHandler RačunPridobiCompleted;
        
        /// <remarks/>
        public event KomitentShraniCompletedEventHandler KomitentShraniCompleted;
        
        /// <remarks/>
        public event KomitentBrišiCompletedEventHandler KomitentBrišiCompleted;
        
        /// <remarks/>
        public event KomitentAžurirajCompletedEventHandler KomitentAžurirajCompleted;
        
        /// <remarks/>
        public event KomitentPridobiCompletedEventHandler KomitentPridobiCompleted;
        
        /// <remarks/>
        public event RačunShraniCompletedEventHandler RačunShraniCompleted;
        
        /// <remarks/>
        public event RačunBrišiCompletedEventHandler RačunBrišiCompleted;
        
        /// <remarks/>
        public event RačunAžurirajCompletedEventHandler RačunAžurirajCompleted;
        
        /// <remarks/>
        public event TransakcijaShraniCompletedEventHandler TransakcijaShraniCompleted;
        
        /// <remarks/>
        public event TransakcijaBrišiCompletedEventHandler TransakcijaBrišiCompleted;
        
        /// <remarks/>
        public event TransakcijaAžurirajCompletedEventHandler TransakcijaAžurirajCompleted;
        
        /// <remarks/>
        public event TransakcijaPridobiCompletedEventHandler TransakcijaPridobiCompleted;
        
        /// <remarks/>
        public event UporabniškiRačunShraniCompletedEventHandler UporabniškiRačunShraniCompleted;
        
        /// <remarks/>
        public event UporabniškiRačunBrišiCompletedEventHandler UporabniškiRačunBrišiCompleted;
        
        /// <remarks/>
        public event UporabniškiRačunAžurirajCompletedEventHandler UporabniškiRačunAžurirajCompleted;
        
        /// <remarks/>
        public event UporabniškiRačunPridobiCompletedEventHandler UporabniškiRačunPridobiCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/prijava", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UporabniskiRacun prijava(string ime, string geslo) {
            object[] results = this.Invoke("prijava", new object[] {
                        ime,
                        geslo});
            return ((UporabniskiRacun)(results[0]));
        }
        
        /// <remarks/>
        public void prijavaAsync(string ime, string geslo) {
            this.prijavaAsync(ime, geslo, null);
        }
        
        /// <remarks/>
        public void prijavaAsync(string ime, string geslo, object userState) {
            if ((this.prijavaOperationCompleted == null)) {
                this.prijavaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprijavaOperationCompleted);
            }
            this.InvokeAsync("prijava", new object[] {
                        ime,
                        geslo}, this.prijavaOperationCompleted, userState);
        }
        
        private void OnprijavaOperationCompleted(object arg) {
            if ((this.prijavaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.prijavaCompleted(this, new prijavaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RačuniKomitenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Račun[] RačuniKomitenta(string davcna) {
            object[] results = this.Invoke("RačuniKomitenta", new object[] {
                        davcna});
            return ((Račun[])(results[0]));
        }
        
        /// <remarks/>
        public void RačuniKomitentaAsync(string davcna) {
            this.RačuniKomitentaAsync(davcna, null);
        }
        
        /// <remarks/>
        public void RačuniKomitentaAsync(string davcna, object userState) {
            if ((this.RačuniKomitentaOperationCompleted == null)) {
                this.RačuniKomitentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRačuniKomitentaOperationCompleted);
            }
            this.InvokeAsync("RačuniKomitenta", new object[] {
                        davcna}, this.RačuniKomitentaOperationCompleted, userState);
        }
        
        private void OnRačuniKomitentaOperationCompleted(object arg) {
            if ((this.RačuniKomitentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RačuniKomitentaCompleted(this, new RačuniKomitentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TransakcijeKomitenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transakcija[] TransakcijeKomitenta(string davcna) {
            object[] results = this.Invoke("TransakcijeKomitenta", new object[] {
                        davcna});
            return ((Transakcija[])(results[0]));
        }
        
        /// <remarks/>
        public void TransakcijeKomitentaAsync(string davcna) {
            this.TransakcijeKomitentaAsync(davcna, null);
        }
        
        /// <remarks/>
        public void TransakcijeKomitentaAsync(string davcna, object userState) {
            if ((this.TransakcijeKomitentaOperationCompleted == null)) {
                this.TransakcijeKomitentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransakcijeKomitentaOperationCompleted);
            }
            this.InvokeAsync("TransakcijeKomitenta", new object[] {
                        davcna}, this.TransakcijeKomitentaOperationCompleted, userState);
        }
        
        private void OnTransakcijeKomitentaOperationCompleted(object arg) {
            if ((this.TransakcijeKomitentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransakcijeKomitentaCompleted(this, new TransakcijeKomitentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeznamTransakcij", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transakcija[] SeznamTransakcij() {
            object[] results = this.Invoke("SeznamTransakcij", new object[0]);
            return ((Transakcija[])(results[0]));
        }
        
        /// <remarks/>
        public void SeznamTransakcijAsync() {
            this.SeznamTransakcijAsync(null);
        }
        
        /// <remarks/>
        public void SeznamTransakcijAsync(object userState) {
            if ((this.SeznamTransakcijOperationCompleted == null)) {
                this.SeznamTransakcijOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeznamTransakcijOperationCompleted);
            }
            this.InvokeAsync("SeznamTransakcij", new object[0], this.SeznamTransakcijOperationCompleted, userState);
        }
        
        private void OnSeznamTransakcijOperationCompleted(object arg) {
            if ((this.SeznamTransakcijCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeznamTransakcijCompleted(this, new SeznamTransakcijCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/seznamRačunov", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Račun[] seznamRačunov() {
            object[] results = this.Invoke("seznamRačunov", new object[0]);
            return ((Račun[])(results[0]));
        }
        
        /// <remarks/>
        public void seznamRačunovAsync() {
            this.seznamRačunovAsync(null);
        }
        
        /// <remarks/>
        public void seznamRačunovAsync(object userState) {
            if ((this.seznamRačunovOperationCompleted == null)) {
                this.seznamRačunovOperationCompleted = new System.Threading.SendOrPostCallback(this.OnseznamRačunovOperationCompleted);
            }
            this.InvokeAsync("seznamRačunov", new object[0], this.seznamRačunovOperationCompleted, userState);
        }
        
        private void OnseznamRačunovOperationCompleted(object arg) {
            if ((this.seznamRačunovCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.seznamRačunovCompleted(this, new seznamRačunovCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeznamKomitentov", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komitent[] SeznamKomitentov() {
            object[] results = this.Invoke("SeznamKomitentov", new object[0]);
            return ((Komitent[])(results[0]));
        }
        
        /// <remarks/>
        public void SeznamKomitentovAsync() {
            this.SeznamKomitentovAsync(null);
        }
        
        /// <remarks/>
        public void SeznamKomitentovAsync(object userState) {
            if ((this.SeznamKomitentovOperationCompleted == null)) {
                this.SeznamKomitentovOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeznamKomitentovOperationCompleted);
            }
            this.InvokeAsync("SeznamKomitentov", new object[0], this.SeznamKomitentovOperationCompleted, userState);
        }
        
        private void OnSeznamKomitentovOperationCompleted(object arg) {
            if ((this.SeznamKomitentovCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeznamKomitentovCompleted(this, new SeznamKomitentovCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vrniTransakcije", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transakcija[] vrniTransakcije() {
            object[] results = this.Invoke("vrniTransakcije", new object[0]);
            return ((Transakcija[])(results[0]));
        }
        
        /// <remarks/>
        public void vrniTransakcijeAsync() {
            this.vrniTransakcijeAsync(null);
        }
        
        /// <remarks/>
        public void vrniTransakcijeAsync(object userState) {
            if ((this.vrniTransakcijeOperationCompleted == null)) {
                this.vrniTransakcijeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvrniTransakcijeOperationCompleted);
            }
            this.InvokeAsync("vrniTransakcije", new object[0], this.vrniTransakcijeOperationCompleted, userState);
        }
        
        private void OnvrniTransakcijeOperationCompleted(object arg) {
            if ((this.vrniTransakcijeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vrniTransakcijeCompleted(this, new vrniTransakcijeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vrniKomitenteZTransakcijo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komitent[] vrniKomitenteZTransakcijo() {
            object[] results = this.Invoke("vrniKomitenteZTransakcijo", new object[0]);
            return ((Komitent[])(results[0]));
        }
        
        /// <remarks/>
        public void vrniKomitenteZTransakcijoAsync() {
            this.vrniKomitenteZTransakcijoAsync(null);
        }
        
        /// <remarks/>
        public void vrniKomitenteZTransakcijoAsync(object userState) {
            if ((this.vrniKomitenteZTransakcijoOperationCompleted == null)) {
                this.vrniKomitenteZTransakcijoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvrniKomitenteZTransakcijoOperationCompleted);
            }
            this.InvokeAsync("vrniKomitenteZTransakcijo", new object[0], this.vrniKomitenteZTransakcijoOperationCompleted, userState);
        }
        
        private void OnvrniKomitenteZTransakcijoOperationCompleted(object arg) {
            if ((this.vrniKomitenteZTransakcijoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vrniKomitenteZTransakcijoCompleted(this, new vrniKomitenteZTransakcijoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/transakcijeKomitenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transakcija[] transakcijeKomitenta(string davcna) {
            object[] results = this.Invoke("transakcijeKomitenta", new object[] {
                        davcna});
            return ((Transakcija[])(results[0]));
        }
        
        /// <remarks/>
        public void transakcijeKomitentaAsync(string davcna) {
            this.transakcijeKomitentaAsync(davcna, null);
        }
        
        /// <remarks/>
        public void transakcijeKomitentaAsync(string davcna, object userState) {
            if ((this.transakcijeKomitentaOperationCompleted == null)) {
                this.transakcijeKomitentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransakcijeKomitentaOperationCompleted);
            }
            this.InvokeAsync("transakcijeKomitenta", new object[] {
                        davcna}, this.transakcijeKomitentaOperationCompleted, userState);
        }
        
        private void OntransakcijeKomitentaOperationCompleted(object arg) {
            if ((this.transakcijeKomitentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transakcijeKomitentaCompleted(this, new transakcijeKomitentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/komitent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komitent komitent(string davcna) {
            object[] results = this.Invoke("komitent", new object[] {
                        davcna});
            return ((Komitent)(results[0]));
        }
        
        /// <remarks/>
        public void komitentAsync(string davcna) {
            this.komitentAsync(davcna, null);
        }
        
        /// <remarks/>
        public void komitentAsync(string davcna, object userState) {
            if ((this.komitentOperationCompleted == null)) {
                this.komitentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnkomitentOperationCompleted);
            }
            this.InvokeAsync("komitent", new object[] {
                        davcna}, this.komitentOperationCompleted, userState);
        }
        
        private void OnkomitentOperationCompleted(object arg) {
            if ((this.komitentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.komitentCompleted(this, new komitentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IzpisBlokiranihRačunov", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Račun[] IzpisBlokiranihRačunov() {
            object[] results = this.Invoke("IzpisBlokiranihRačunov", new object[0]);
            return ((Račun[])(results[0]));
        }
        
        /// <remarks/>
        public void IzpisBlokiranihRačunovAsync() {
            this.IzpisBlokiranihRačunovAsync(null);
        }
        
        /// <remarks/>
        public void IzpisBlokiranihRačunovAsync(object userState) {
            if ((this.IzpisBlokiranihRačunovOperationCompleted == null)) {
                this.IzpisBlokiranihRačunovOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIzpisBlokiranihRačunovOperationCompleted);
            }
            this.InvokeAsync("IzpisBlokiranihRačunov", new object[0], this.IzpisBlokiranihRačunovOperationCompleted, userState);
        }
        
        private void OnIzpisBlokiranihRačunovOperationCompleted(object arg) {
            if ((this.IzpisBlokiranihRačunovCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IzpisBlokiranihRačunovCompleted(this, new IzpisBlokiranihRačunovCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NajvišjaTransakcija", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transakcija NajvišjaTransakcija() {
            object[] results = this.Invoke("NajvišjaTransakcija", new object[0]);
            return ((Transakcija)(results[0]));
        }
        
        /// <remarks/>
        public void NajvišjaTransakcijaAsync() {
            this.NajvišjaTransakcijaAsync(null);
        }
        
        /// <remarks/>
        public void NajvišjaTransakcijaAsync(object userState) {
            if ((this.NajvišjaTransakcijaOperationCompleted == null)) {
                this.NajvišjaTransakcijaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNajvišjaTransakcijaOperationCompleted);
            }
            this.InvokeAsync("NajvišjaTransakcija", new object[0], this.NajvišjaTransakcijaOperationCompleted, userState);
        }
        
        private void OnNajvišjaTransakcijaOperationCompleted(object arg) {
            if ((this.NajvišjaTransakcijaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NajvišjaTransakcijaCompleted(this, new NajvišjaTransakcijaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/povprecnaStarostKomitentov", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double povprecnaStarostKomitentov() {
            object[] results = this.Invoke("povprecnaStarostKomitentov", new object[0]);
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void povprecnaStarostKomitentovAsync() {
            this.povprecnaStarostKomitentovAsync(null);
        }
        
        /// <remarks/>
        public void povprecnaStarostKomitentovAsync(object userState) {
            if ((this.povprecnaStarostKomitentovOperationCompleted == null)) {
                this.povprecnaStarostKomitentovOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpovprecnaStarostKomitentovOperationCompleted);
            }
            this.InvokeAsync("povprecnaStarostKomitentov", new object[0], this.povprecnaStarostKomitentovOperationCompleted, userState);
        }
        
        private void OnpovprecnaStarostKomitentovOperationCompleted(object arg) {
            if ((this.povprecnaStarostKomitentovCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.povprecnaStarostKomitentovCompleted(this, new povprecnaStarostKomitentovCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RačunPridobi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Račun RačunPridobi(Komitent kom, int idRač) {
            object[] results = this.Invoke("RačunPridobi", new object[] {
                        kom,
                        idRač});
            return ((Račun)(results[0]));
        }
        
        /// <remarks/>
        public void RačunPridobiAsync(Komitent kom, int idRač) {
            this.RačunPridobiAsync(kom, idRač, null);
        }
        
        /// <remarks/>
        public void RačunPridobiAsync(Komitent kom, int idRač, object userState) {
            if ((this.RačunPridobiOperationCompleted == null)) {
                this.RačunPridobiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRačunPridobiOperationCompleted);
            }
            this.InvokeAsync("RačunPridobi", new object[] {
                        kom,
                        idRač}, this.RačunPridobiOperationCompleted, userState);
        }
        
        private void OnRačunPridobiOperationCompleted(object arg) {
            if ((this.RačunPridobiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RačunPridobiCompleted(this, new RačunPridobiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KomitentShrani", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KomitentShrani(Komitent kom) {
            this.Invoke("KomitentShrani", new object[] {
                        kom});
        }
        
        /// <remarks/>
        public void KomitentShraniAsync(Komitent kom) {
            this.KomitentShraniAsync(kom, null);
        }
        
        /// <remarks/>
        public void KomitentShraniAsync(Komitent kom, object userState) {
            if ((this.KomitentShraniOperationCompleted == null)) {
                this.KomitentShraniOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKomitentShraniOperationCompleted);
            }
            this.InvokeAsync("KomitentShrani", new object[] {
                        kom}, this.KomitentShraniOperationCompleted, userState);
        }
        
        private void OnKomitentShraniOperationCompleted(object arg) {
            if ((this.KomitentShraniCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KomitentShraniCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KomitentBriši", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KomitentBriši(Komitent kom) {
            this.Invoke("KomitentBriši", new object[] {
                        kom});
        }
        
        /// <remarks/>
        public void KomitentBrišiAsync(Komitent kom) {
            this.KomitentBrišiAsync(kom, null);
        }
        
        /// <remarks/>
        public void KomitentBrišiAsync(Komitent kom, object userState) {
            if ((this.KomitentBrišiOperationCompleted == null)) {
                this.KomitentBrišiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKomitentBrišiOperationCompleted);
            }
            this.InvokeAsync("KomitentBriši", new object[] {
                        kom}, this.KomitentBrišiOperationCompleted, userState);
        }
        
        private void OnKomitentBrišiOperationCompleted(object arg) {
            if ((this.KomitentBrišiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KomitentBrišiCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KomitentAžuriraj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KomitentAžuriraj(Komitent kom) {
            this.Invoke("KomitentAžuriraj", new object[] {
                        kom});
        }
        
        /// <remarks/>
        public void KomitentAžurirajAsync(Komitent kom) {
            this.KomitentAžurirajAsync(kom, null);
        }
        
        /// <remarks/>
        public void KomitentAžurirajAsync(Komitent kom, object userState) {
            if ((this.KomitentAžurirajOperationCompleted == null)) {
                this.KomitentAžurirajOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKomitentAžurirajOperationCompleted);
            }
            this.InvokeAsync("KomitentAžuriraj", new object[] {
                        kom}, this.KomitentAžurirajOperationCompleted, userState);
        }
        
        private void OnKomitentAžurirajOperationCompleted(object arg) {
            if ((this.KomitentAžurirajCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KomitentAžurirajCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KomitentPridobi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Komitent KomitentPridobi(int idKomitenta) {
            object[] results = this.Invoke("KomitentPridobi", new object[] {
                        idKomitenta});
            return ((Komitent)(results[0]));
        }
        
        /// <remarks/>
        public void KomitentPridobiAsync(int idKomitenta) {
            this.KomitentPridobiAsync(idKomitenta, null);
        }
        
        /// <remarks/>
        public void KomitentPridobiAsync(int idKomitenta, object userState) {
            if ((this.KomitentPridobiOperationCompleted == null)) {
                this.KomitentPridobiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKomitentPridobiOperationCompleted);
            }
            this.InvokeAsync("KomitentPridobi", new object[] {
                        idKomitenta}, this.KomitentPridobiOperationCompleted, userState);
        }
        
        private void OnKomitentPridobiOperationCompleted(object arg) {
            if ((this.KomitentPridobiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KomitentPridobiCompleted(this, new KomitentPridobiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RačunShrani", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RačunShrani(Račun rač) {
            this.Invoke("RačunShrani", new object[] {
                        rač});
        }
        
        /// <remarks/>
        public void RačunShraniAsync(Račun rač) {
            this.RačunShraniAsync(rač, null);
        }
        
        /// <remarks/>
        public void RačunShraniAsync(Račun rač, object userState) {
            if ((this.RačunShraniOperationCompleted == null)) {
                this.RačunShraniOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRačunShraniOperationCompleted);
            }
            this.InvokeAsync("RačunShrani", new object[] {
                        rač}, this.RačunShraniOperationCompleted, userState);
        }
        
        private void OnRačunShraniOperationCompleted(object arg) {
            if ((this.RačunShraniCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RačunShraniCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RačunBriši", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RačunBriši(Račun rač) {
            this.Invoke("RačunBriši", new object[] {
                        rač});
        }
        
        /// <remarks/>
        public void RačunBrišiAsync(Račun rač) {
            this.RačunBrišiAsync(rač, null);
        }
        
        /// <remarks/>
        public void RačunBrišiAsync(Račun rač, object userState) {
            if ((this.RačunBrišiOperationCompleted == null)) {
                this.RačunBrišiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRačunBrišiOperationCompleted);
            }
            this.InvokeAsync("RačunBriši", new object[] {
                        rač}, this.RačunBrišiOperationCompleted, userState);
        }
        
        private void OnRačunBrišiOperationCompleted(object arg) {
            if ((this.RačunBrišiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RačunBrišiCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RačunAžuriraj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RačunAžuriraj(Račun rač) {
            this.Invoke("RačunAžuriraj", new object[] {
                        rač});
        }
        
        /// <remarks/>
        public void RačunAžurirajAsync(Račun rač) {
            this.RačunAžurirajAsync(rač, null);
        }
        
        /// <remarks/>
        public void RačunAžurirajAsync(Račun rač, object userState) {
            if ((this.RačunAžurirajOperationCompleted == null)) {
                this.RačunAžurirajOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRačunAžurirajOperationCompleted);
            }
            this.InvokeAsync("RačunAžuriraj", new object[] {
                        rač}, this.RačunAžurirajOperationCompleted, userState);
        }
        
        private void OnRačunAžurirajOperationCompleted(object arg) {
            if ((this.RačunAžurirajCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RačunAžurirajCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TransakcijaShrani", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TransakcijaShrani(Transakcija tra) {
            this.Invoke("TransakcijaShrani", new object[] {
                        tra});
        }
        
        /// <remarks/>
        public void TransakcijaShraniAsync(Transakcija tra) {
            this.TransakcijaShraniAsync(tra, null);
        }
        
        /// <remarks/>
        public void TransakcijaShraniAsync(Transakcija tra, object userState) {
            if ((this.TransakcijaShraniOperationCompleted == null)) {
                this.TransakcijaShraniOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransakcijaShraniOperationCompleted);
            }
            this.InvokeAsync("TransakcijaShrani", new object[] {
                        tra}, this.TransakcijaShraniOperationCompleted, userState);
        }
        
        private void OnTransakcijaShraniOperationCompleted(object arg) {
            if ((this.TransakcijaShraniCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransakcijaShraniCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TransakcijaBriši", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TransakcijaBriši(Transakcija tra) {
            this.Invoke("TransakcijaBriši", new object[] {
                        tra});
        }
        
        /// <remarks/>
        public void TransakcijaBrišiAsync(Transakcija tra) {
            this.TransakcijaBrišiAsync(tra, null);
        }
        
        /// <remarks/>
        public void TransakcijaBrišiAsync(Transakcija tra, object userState) {
            if ((this.TransakcijaBrišiOperationCompleted == null)) {
                this.TransakcijaBrišiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransakcijaBrišiOperationCompleted);
            }
            this.InvokeAsync("TransakcijaBriši", new object[] {
                        tra}, this.TransakcijaBrišiOperationCompleted, userState);
        }
        
        private void OnTransakcijaBrišiOperationCompleted(object arg) {
            if ((this.TransakcijaBrišiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransakcijaBrišiCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TransakcijaAžuriraj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TransakcijaAžuriraj(Transakcija tra) {
            this.Invoke("TransakcijaAžuriraj", new object[] {
                        tra});
        }
        
        /// <remarks/>
        public void TransakcijaAžurirajAsync(Transakcija tra) {
            this.TransakcijaAžurirajAsync(tra, null);
        }
        
        /// <remarks/>
        public void TransakcijaAžurirajAsync(Transakcija tra, object userState) {
            if ((this.TransakcijaAžurirajOperationCompleted == null)) {
                this.TransakcijaAžurirajOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransakcijaAžurirajOperationCompleted);
            }
            this.InvokeAsync("TransakcijaAžuriraj", new object[] {
                        tra}, this.TransakcijaAžurirajOperationCompleted, userState);
        }
        
        private void OnTransakcijaAžurirajOperationCompleted(object arg) {
            if ((this.TransakcijaAžurirajCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransakcijaAžurirajCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TransakcijaPridobi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transakcija TransakcijaPridobi(int transakcijaId) {
            object[] results = this.Invoke("TransakcijaPridobi", new object[] {
                        transakcijaId});
            return ((Transakcija)(results[0]));
        }
        
        /// <remarks/>
        public void TransakcijaPridobiAsync(int transakcijaId) {
            this.TransakcijaPridobiAsync(transakcijaId, null);
        }
        
        /// <remarks/>
        public void TransakcijaPridobiAsync(int transakcijaId, object userState) {
            if ((this.TransakcijaPridobiOperationCompleted == null)) {
                this.TransakcijaPridobiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransakcijaPridobiOperationCompleted);
            }
            this.InvokeAsync("TransakcijaPridobi", new object[] {
                        transakcijaId}, this.TransakcijaPridobiOperationCompleted, userState);
        }
        
        private void OnTransakcijaPridobiOperationCompleted(object arg) {
            if ((this.TransakcijaPridobiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransakcijaPridobiCompleted(this, new TransakcijaPridobiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UporabniškiRačunShrani", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UporabniškiRačunShrani(UporabniskiRacun upoRac) {
            this.Invoke("UporabniškiRačunShrani", new object[] {
                        upoRac});
        }
        
        /// <remarks/>
        public void UporabniškiRačunShraniAsync(UporabniskiRacun upoRac) {
            this.UporabniškiRačunShraniAsync(upoRac, null);
        }
        
        /// <remarks/>
        public void UporabniškiRačunShraniAsync(UporabniskiRacun upoRac, object userState) {
            if ((this.UporabniškiRačunShraniOperationCompleted == null)) {
                this.UporabniškiRačunShraniOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUporabniškiRačunShraniOperationCompleted);
            }
            this.InvokeAsync("UporabniškiRačunShrani", new object[] {
                        upoRac}, this.UporabniškiRačunShraniOperationCompleted, userState);
        }
        
        private void OnUporabniškiRačunShraniOperationCompleted(object arg) {
            if ((this.UporabniškiRačunShraniCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UporabniškiRačunShraniCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UporabniškiRačunBriši", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UporabniškiRačunBriši(UporabniskiRacun upoRac) {
            this.Invoke("UporabniškiRačunBriši", new object[] {
                        upoRac});
        }
        
        /// <remarks/>
        public void UporabniškiRačunBrišiAsync(UporabniskiRacun upoRac) {
            this.UporabniškiRačunBrišiAsync(upoRac, null);
        }
        
        /// <remarks/>
        public void UporabniškiRačunBrišiAsync(UporabniskiRacun upoRac, object userState) {
            if ((this.UporabniškiRačunBrišiOperationCompleted == null)) {
                this.UporabniškiRačunBrišiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUporabniškiRačunBrišiOperationCompleted);
            }
            this.InvokeAsync("UporabniškiRačunBriši", new object[] {
                        upoRac}, this.UporabniškiRačunBrišiOperationCompleted, userState);
        }
        
        private void OnUporabniškiRačunBrišiOperationCompleted(object arg) {
            if ((this.UporabniškiRačunBrišiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UporabniškiRačunBrišiCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UporabniškiRačunAžuriraj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UporabniškiRačunAžuriraj(UporabniskiRacun upoRac) {
            this.Invoke("UporabniškiRačunAžuriraj", new object[] {
                        upoRac});
        }
        
        /// <remarks/>
        public void UporabniškiRačunAžurirajAsync(UporabniskiRacun upoRac) {
            this.UporabniškiRačunAžurirajAsync(upoRac, null);
        }
        
        /// <remarks/>
        public void UporabniškiRačunAžurirajAsync(UporabniskiRacun upoRac, object userState) {
            if ((this.UporabniškiRačunAžurirajOperationCompleted == null)) {
                this.UporabniškiRačunAžurirajOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUporabniškiRačunAžurirajOperationCompleted);
            }
            this.InvokeAsync("UporabniškiRačunAžuriraj", new object[] {
                        upoRac}, this.UporabniškiRačunAžurirajOperationCompleted, userState);
        }
        
        private void OnUporabniškiRačunAžurirajOperationCompleted(object arg) {
            if ((this.UporabniškiRačunAžurirajCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UporabniškiRačunAžurirajCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UporabniškiRačunPridobi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UporabniskiRacun UporabniškiRačunPridobi(int uporacID) {
            object[] results = this.Invoke("UporabniškiRačunPridobi", new object[] {
                        uporacID});
            return ((UporabniskiRacun)(results[0]));
        }
        
        /// <remarks/>
        public void UporabniškiRačunPridobiAsync(int uporacID) {
            this.UporabniškiRačunPridobiAsync(uporacID, null);
        }
        
        /// <remarks/>
        public void UporabniškiRačunPridobiAsync(int uporacID, object userState) {
            if ((this.UporabniškiRačunPridobiOperationCompleted == null)) {
                this.UporabniškiRačunPridobiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUporabniškiRačunPridobiOperationCompleted);
            }
            this.InvokeAsync("UporabniškiRačunPridobi", new object[] {
                        uporacID}, this.UporabniškiRačunPridobiOperationCompleted, userState);
        }
        
        private void OnUporabniškiRačunPridobiOperationCompleted(object arg) {
            if ((this.UporabniškiRačunPridobiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UporabniškiRačunPridobiCompleted(this, new UporabniškiRačunPridobiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UporabniskiRacun {
        
        private int uporabniskiRacunIdField;
        
        private string imeField;
        
        private string gesloField;
        
        private bool aliJeAdminField;
        
        /// <remarks/>
        public int UporabniskiRacunId {
            get {
                return this.uporabniskiRacunIdField;
            }
            set {
                this.uporabniskiRacunIdField = value;
            }
        }
        
        /// <remarks/>
        public string ime {
            get {
                return this.imeField;
            }
            set {
                this.imeField = value;
            }
        }
        
        /// <remarks/>
        public string geslo {
            get {
                return this.gesloField;
            }
            set {
                this.gesloField = value;
            }
        }
        
        /// <remarks/>
        public bool aliJeAdmin {
            get {
                return this.aliJeAdminField;
            }
            set {
                this.aliJeAdminField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Transakcija {
        
        private int transakcijaIdField;
        
        private System.DateTime datumTransakcijeField;
        
        private double znesekField;
        
        private Račun računField;
        
        /// <remarks/>
        public int TransakcijaId {
            get {
                return this.transakcijaIdField;
            }
            set {
                this.transakcijaIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime datumTransakcije {
            get {
                return this.datumTransakcijeField;
            }
            set {
                this.datumTransakcijeField = value;
            }
        }
        
        /// <remarks/>
        public double znesek {
            get {
                return this.znesekField;
            }
            set {
                this.znesekField = value;
            }
        }
        
        /// <remarks/>
        public Račun račun {
            get {
                return this.računField;
            }
            set {
                this.računField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Račun {
        
        private int računIdField;
        
        private Komitent lastnikField;
        
        private double stanjeField;
        
        private double limitField;
        
        private bool blokiranField;
        
        private string bankaField;
        
        /// <remarks/>
        public int RačunId {
            get {
                return this.računIdField;
            }
            set {
                this.računIdField = value;
            }
        }
        
        /// <remarks/>
        public Komitent lastnik {
            get {
                return this.lastnikField;
            }
            set {
                this.lastnikField = value;
            }
        }
        
        /// <remarks/>
        public double stanje {
            get {
                return this.stanjeField;
            }
            set {
                this.stanjeField = value;
            }
        }
        
        /// <remarks/>
        public double limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
            }
        }
        
        /// <remarks/>
        public bool blokiran {
            get {
                return this.blokiranField;
            }
            set {
                this.blokiranField = value;
            }
        }
        
        /// <remarks/>
        public string Banka {
            get {
                return this.bankaField;
            }
            set {
                this.bankaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Komitent {
        
        private int komitentIdField;
        
        private string imeField;
        
        private string priimekField;
        
        private string davcnaStevilkaField;
        
        private System.DateTime datumRojstvaField;
        
        /// <remarks/>
        public int KomitentId {
            get {
                return this.komitentIdField;
            }
            set {
                this.komitentIdField = value;
            }
        }
        
        /// <remarks/>
        public string Ime {
            get {
                return this.imeField;
            }
            set {
                this.imeField = value;
            }
        }
        
        /// <remarks/>
        public string Priimek {
            get {
                return this.priimekField;
            }
            set {
                this.priimekField = value;
            }
        }
        
        /// <remarks/>
        public string DavcnaStevilka {
            get {
                return this.davcnaStevilkaField;
            }
            set {
                this.davcnaStevilkaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DatumRojstva {
            get {
                return this.datumRojstvaField;
            }
            set {
                this.datumRojstvaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void prijavaCompletedEventHandler(object sender, prijavaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class prijavaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal prijavaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UporabniskiRacun Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UporabniskiRacun)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RačuniKomitentaCompletedEventHandler(object sender, RačuniKomitentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RačuniKomitentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RačuniKomitentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Račun[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Račun[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void TransakcijeKomitentaCompletedEventHandler(object sender, TransakcijeKomitentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransakcijeKomitentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TransakcijeKomitentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transakcija[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transakcija[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SeznamTransakcijCompletedEventHandler(object sender, SeznamTransakcijCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeznamTransakcijCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeznamTransakcijCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transakcija[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transakcija[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void seznamRačunovCompletedEventHandler(object sender, seznamRačunovCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seznamRačunovCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal seznamRačunovCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Račun[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Račun[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SeznamKomitentovCompletedEventHandler(object sender, SeznamKomitentovCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeznamKomitentovCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeznamKomitentovCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komitent[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komitent[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void vrniTransakcijeCompletedEventHandler(object sender, vrniTransakcijeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vrniTransakcijeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vrniTransakcijeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transakcija[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transakcija[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void vrniKomitenteZTransakcijoCompletedEventHandler(object sender, vrniKomitenteZTransakcijoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vrniKomitenteZTransakcijoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vrniKomitenteZTransakcijoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komitent[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komitent[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void transakcijeKomitentaCompletedEventHandler(object sender, transakcijeKomitentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transakcijeKomitentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transakcijeKomitentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transakcija[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transakcija[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void komitentCompletedEventHandler(object sender, komitentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class komitentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal komitentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komitent Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komitent)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IzpisBlokiranihRačunovCompletedEventHandler(object sender, IzpisBlokiranihRačunovCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IzpisBlokiranihRačunovCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IzpisBlokiranihRačunovCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Račun[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Račun[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void NajvišjaTransakcijaCompletedEventHandler(object sender, NajvišjaTransakcijaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NajvišjaTransakcijaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NajvišjaTransakcijaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transakcija Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transakcija)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void povprecnaStarostKomitentovCompletedEventHandler(object sender, povprecnaStarostKomitentovCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class povprecnaStarostKomitentovCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal povprecnaStarostKomitentovCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RačunPridobiCompletedEventHandler(object sender, RačunPridobiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RačunPridobiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RačunPridobiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Račun Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Račun)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void KomitentShraniCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void KomitentBrišiCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void KomitentAžurirajCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void KomitentPridobiCompletedEventHandler(object sender, KomitentPridobiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KomitentPridobiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KomitentPridobiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Komitent Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Komitent)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RačunShraniCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RačunBrišiCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RačunAžurirajCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void TransakcijaShraniCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void TransakcijaBrišiCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void TransakcijaAžurirajCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void TransakcijaPridobiCompletedEventHandler(object sender, TransakcijaPridobiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransakcijaPridobiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TransakcijaPridobiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transakcija Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transakcija)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UporabniškiRačunShraniCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UporabniškiRačunBrišiCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UporabniškiRačunAžurirajCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UporabniškiRačunPridobiCompletedEventHandler(object sender, UporabniškiRačunPridobiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UporabniškiRačunPridobiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UporabniškiRačunPridobiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UporabniskiRacun Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UporabniskiRacun)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591