use mydb;
DROP TABLE IF EXISTS artikel_ima_cena;
DROP TABLE IF EXISTS cena;
DROP TABLE IF EXISTS miza;
DROP TABLE IF EXISTS jed_na_racun;
DROP TABLE IF EXISTS sestavine;
DROP TABLE IF EXISTS artikel;
DROP TABLE IF EXISTS enota;
DROP TABLE IF EXISTS narocilo;
DROP TABLE IF EXISTS racun;
DROP TABLE IF EXISTS jed;
DROP TABLE IF EXISTS vrsta_jedi;
DROP TABLE IF EXISTS skupina;
DROP TABLE IF EXISTS oseba;
DROP TABLE IF EXISTS naslov;
DROP TABLE IF EXISTS vloga_osebe;
DROP TABLE IF EXISTS posta;
DROP TABLE IF EXISTS log_artikel;
DROP TABLE IF EXISTS log_oseba;


DROP SCHEMA IF EXISTS `mydb` ;